type ProductData = {
  Id: string;
  Stockcode: number;
  Name: string;
  DisplayName?: string;
  UrlFriendlyName?: string; // kebab-case
  Description: string;
  RichDescription: string;
  Brand: string;
  AdditionalAttributes: AdditionalAttributes;

  // Buying measure
  Price: number;
  InstorePrice: number;
  IsOnSpecial: boolean;
  Unit: "Each";
  PackageSize: "500g";

  SmallImageFile: string; //url
  MediumImageFile: string; //url
  LargeImageFile: string; //url

  NutritionalInformation: NutritionalInformation[];
};

type AdditionalAttributes = {
  ingredients: string; // comma separated
  nutritionalinformation: string; // json string
};

type NutritionalInformation = {
  Name: string;
  Values: {
    "Quantity Per Serving": string;
    "Quantity Per 100g / 100mL": string;
  };
  ServingSize: string;
  ServingsPerPack: string;
};

export const response = {
  Product: {
    TileID: 0,
    Stockcode: 919417,
    Barcode: "9339423008715",
    GtinFormat: 13,
    CupPrice: 1.38,
    InstoreCupPrice: 1.38,
    CupMeasure: "100G",
    CupString: "$1.38 / 100G",
    InstoreCupString: "$1.38 / 100G",
    HasCupPrice: true,
    InstoreHasCupPrice: true,
    Price: 6.9,
    InstorePrice: 6.9,
    Name: "Tip Top Bakery Cafe Coconut & Cranberry Bread Loaf Thick Cut",
    DisplayName:
      "Tip Top Bakery Cafe Coconut & Cranberry Bread Loaf Thick Cut 500g",
    UrlFriendlyName:
      "tip-top-bakery-cafe-coconut-cranberry-bread-loaf-thick-cut",
    Description: " Tip Top Bakery Cafe Coconut<br>& Cranberry Bread... 500g",
    SmallImageFile:
      "https://cdn0.woolworths.media/content/wowproductimages/small/919417.jpg",
    MediumImageFile:
      "https://cdn0.woolworths.media/content/wowproductimages/medium/919417.jpg",
    LargeImageFile:
      "https://cdn0.woolworths.media/content/wowproductimages/large/919417.jpg",
    IsNew: false,
    IsHalfPrice: false,
    IsOnlineOnly: false,
    IsOnSpecial: false,
    InstoreIsOnSpecial: false,
    IsEdrSpecial: false,
    SavingsAmount: 0.0,
    InstoreSavingsAmount: 0.0,
    WasPrice: 6.9,
    InstoreWasPrice: 6.9,
    QuantityInTrolley: 0,
    Unit: "Each",
    MinimumQuantity: 1,
    HasBeenBoughtBefore: false,
    IsInTrolley: false,
    Source: "ProductDetail",
    SupplyLimit: 36,
    ProductLimit: 36,
    MaxSupplyLimitMessage: "36 item limit",
    IsRanged: true,
    IsInStock: true,
    PackageSize: "500g",
    IsPmDelivery: false,
    IsForCollection: true,
    IsForDelivery: true,
    IsForExpress: true,
    ProductRestrictionMessage: null,
    ProductWarningMessage: null,
    CentreTag: {
      TagContent:
        '<a title="Earn Bonus Card Pack^" href="/Shop/ProductGroup/411341"><span>Earn Bonus Card Pack^ </span><i aria-hidden="true" class="iconAct-Chevron_Right"></i></a>',
      TagLink: null,
      FallbackText: null,
      TagType: "Html",
      MultibuyData: null,
      MemberPriceData: null,
      TagContentText: "Earn Bonus Card Pack^ ",
      DualImageTagContent: null,
      PromotionType: "NOT_SET",
      IsRegisteredRewardCardPromotion: false,
    },
    IsCentreTag: true,
    ImageTag: {
      TagContent:
        "/content/promotiontags/jupiter-roundel-hexagon-buy1-200x200.png",
      TagLink: null,
      FallbackText: "Buy 1 Get 1 bonus card pack ^",
      TagType: "None",
      MultibuyData: null,
      MemberPriceData: null,
      TagContentText: null,
      DualImageTagContent: null,
      PromotionType: "NOT_SET",
      IsRegisteredRewardCardPromotion: false,
    },
    HeaderTag: null,
    HasHeaderTag: false,
    UnitWeightInGrams: 535,
    SupplyLimitMessage:
      "'Tip Top Bakery Cafe Coconut & Cranberry Bread Loaf Thick Cut' has a supply limit of 36. The quantity in your cart has been reduced accordingly. To purchase a larger quantity, please contact us on 1800 000 610. Please note we do not supply trade orders.",
    SmallFormatDescription:
      "Tip Top Bakery Cafe Coconut & Cranberry Bread Loaf Thick Cut",
    FullDescription:
      "Tip Top Bakery Cafe Coconut & Cranberry Bread Loaf Thick Cut",
    IsAvailable: true,
    InstoreIsAvailable: false,
    IsPurchasable: true,
    InstoreIsPurchasable: false,
    AgeRestricted: false,
    DisplayQuantity: 1,
    RichDescription:
      "<br><br>Create a Café classic at home with the fruity, delicious thick-cut slices of the Tip Top Café range. Made with real fruit and full of sweet cranberries and luscious coconut. This product is limited time only, so try it quick!<br><br>Limited Edition<br><br>Made with Sweet Cranberries and Luscious Coconut<br><br>Proudly baked with Aussie Wheat<br><br>Thick cut slices",
    HideWasSavedPrice: false,
    SapCategories: {
      SapDepartmentName: "PROPRIETARY BAKERY",
      SapCategoryName: "PROPRIETARY BAKERY",
      SapSubCategoryName: "RESALE BAKERY SNACKS",
      SapSegmentName: "FRUIT LOAF/SCONE",
    },
    Brand: "Tip Top Bakery",
    IsRestrictedByDeliveryMethod: false,
    FooterTag: {
      TagContent: null,
      TagLink: null,
      FallbackText: null,
      TagType: "None",
      MultibuyData: null,
      MemberPriceData: null,
      TagContentText: null,
      DualImageTagContent: null,
      PromotionType: "NOT_SET",
      IsRegisteredRewardCardPromotion: false,
    },
    IsFooterEnabled: false,
    Diagnostics: "0",
    IsBundle: false,
    IsInFamily: false,
    ChildProducts: [],
    UrlOverride: null,
    AdditionalAttributes: {
      boxedcontents: null,
      addedvitaminsandminerals: "False",
      sapdepartmentname: "PROPRIETARY BAKERY",
      spf: null,
      haircolour: null,
      lifestyleanddietarystatement: "Halal",
      sapcategoryname: "PROPRIETARY BAKERY",
      skintype: null,
      importantinformation: null,
      allergystatement:
        "Dairy Free,Egg Free,Fish Free,Lactose Free,No Artificial Colours or Flavours,No Artificial Preservatives",
      productdepthmm: null,
      skincondition: null,
      ophthalmologistapproved: null,
      healthstarrating: "3",
      hairtype: null,
      "fragrance-free": null,
      sapsegmentname: "FRUIT LOAF/SCONE",
      suitablefor: null,
      PiesProductDepartmentsjson: '[{"Id":"1_DEB537E","Description":"Bakery"}]',
      piessubcategorynamesjson: '["Muffins, Scones & Cupcakes"]',
      sapsegmentno: "7",
      productwidthmm: null,
      contains: null,
      sapsubcategoryname: "RESALE BAKERY SNACKS",
      dermatologisttested: null,
      wool_productpackaging: null,
      dermatologicallyapproved: null,
      specialsgroupid: null,
      productimages:
        "919417.jpg,919417_2.jpg,919417_3.jpg,919417_4.jpg,919417_6.jpg",
      productheightmm: null,
      "r&r_hidereviews": null,
      microwavesafe: "False",
      "paba-free": null,
      lifestyleclaim: "HALAL",
      alcoholfree: null,
      tgawarning: null,
      activeconstituents: null,
      microwaveable: "False",
      "soap-free": null,
      countryoforigin: null,
      isexcludedfromsubstitution: "False",
      productimagecount: "5",
      "r&r_loggedinreviews": null,
      "anti-dandruff": null,
      "servingsize-total-nip": null,
      tgahealthwarninglink: null,
      allergenmaybepresent: "Sesame",
      PiesProductDepartmentNodeId: "1_DEB537E",
      parabenfree: "False",
      vendorarticleid: null,
      containsgluten: "False",
      containsnuts: "False",
      ingredients:
        "Flour, Water, Dried Sweetened Cranberries  Cranberries (5%), Sugar, Canola Oil, Wheat Gluten, Vinegar, Iodised Salt, Soy Flour, Fermented Wheat Flour, Natural Flavouring, Vegetable Emulsifiers ( 481, 472e), Vitamins (Thiamin, Folic Acid), Processing Aid (Wheat).",
      colour: null,
      manufacturer: null,
      sapcategoryno: "60",
      storageinstructions:
        "Store in a cool, dry place away from direct sunlight.",
      tgawarnings: null,
      piesdepartmentnamesjson: '["Bakery"]',
      brand: "tip top bakery",
      oilfree: null,
      fragrance: null,
      antibacterial: "False",
      "non-comedogenic": null,
      antiseptic: "False",
      bpafree: "False",
      vendorcostprice: null,
      description:
        "<br><br>Create a Café classic at home with the fruity, delicious thick-cut slices of the Tip Top Café range. Made with real fruit and full of sweet cranberries and luscious coconut. This product is limited time only, so try it quick!<br><br>Limited Edition<br><br>Made with Sweet Cranberries and Luscious Coconut<br><br>Proudly baked with Aussie Wheat<br><br>Thick cut slices",
      sweatresistant: null,
      sapsubcategoryno: "949",
      antioxidant: "False",
      claims: null,
      phbalanced: null,
      wool_dietaryclaim: null,
      ophthalmologisttested: null,
      sulfatefree: "False",
      piescategorynamesjson: '["Packaged Bread & Bakery"]',
      "servingsperpack-total-nip": null,
      nutritionalinformation:
        '{"Name":"Nutritional Information","Attributes":[{"Id":705,"Name":"Carbohydrate Quantity Per 100g - Total - NIP","Value":"45.4g","Description":"Carbohydrate Quantity Per 100g - Total - NIP","SortOrder":83},{"Id":706,"Name":"Carbohydrate Quantity Per Serve - Total - NIP","Value":"22.7g","Description":"Carbohydrate Quantity Per Serve - Total - NIP","SortOrder":87},{"Id":191,"Name":"Dietary Fibre Quantity Per 100g - Total - NIP","Value":"3.7g","Description":"Dietary Fibre Quantity Per 100g - Total - NIP","SortOrder":175},{"Id":120,"Name":"Dietary Fibre Quantity Per Serve - Total - NIP","Value":"1.8g","Description":"Dietary Fibre Quantity Per Serve - Total - NIP","SortOrder":179},{"Id":759,"Name":"Energy kJ Quantity Per 100g - Total - NIP","Value":"1210.0kJ","Description":"Energy kJ Quantity Per 100g - Total - NIP","SortOrder":239},{"Id":760,"Name":"Energy kJ Quantity Per Serve - Total - NIP","Value":"605.0kJ","Description":"Energy kJ Quantity Per Serve - Total - NIP","SortOrder":243},{"Id":253,"Name":"Fat Saturated Quantity Per 100g - Total - NIP","Value":"3.8g","Description":"Fat Saturated Quantity Per 100g - Total - NIP","SortOrder":251},{"Id":258,"Name":"Fat Saturated Quantity Per Serve - Total - NIP","Value":"1.9g","Description":"Fat Saturated Quantity Per Serve - Total - NIP","SortOrder":255},{"Id":764,"Name":"Fat Total Quantity Per 100g - Total - NIP","Value":"6.9g","Description":"Fat Total Quantity Per 100g - Total - NIP","SortOrder":263},{"Id":166,"Name":"Fat Total Quantity Per 100g - ValueWord - NIP","Value":"6.9","Description":"Fat Total Quantity Per 100g - ValueWord - NIP","SortOrder":264},{"Id":264,"Name":"Fat Total Quantity Per Serve - Total - NIP","Value":"3.4g","Description":"Fat Total Quantity Per Serve - Total - NIP","SortOrder":267},{"Id":878,"Name":"Protein Quantity Per 100g - Total - NIP","Value":"9.2g","Description":"Protein Quantity Per 100g - Total - NIP","SortOrder":587},{"Id":882,"Name":"Protein Quantity Per Serve - Total - NIP","Value":"4.6g","Description":"Protein Quantity Per Serve - Total - NIP","SortOrder":591},{"Id":477,"Name":"Serving Size - Total - NIP","Value":"50.0 G","Description":"Serving Size - Total - NIP","SortOrder":607},{"Id":544,"Name":"Servings Per Pack - Total - NIP","Value":"10.0","Description":"Servings Per Pack - Total - NIP","SortOrder":611},{"Id":491,"Name":"Sodium Quantity Per 100g - Total - NIP","Value":"306.0mg","Description":"Sodium Quantity Per 100g - Total - NIP","SortOrder":623},{"Id":495,"Name":"Sodium Quantity Per Serve - Total - NIP","Value":"153.0mg","Description":"Sodium Quantity Per Serve - Total - NIP","SortOrder":627},{"Id":908,"Name":"Sugars Quantity Per 100g - SuffixUnits - NIP","Value":"g","Description":"Sugars Quantity Per 100g - SuffixUnits - NIP","SortOrder":646},{"Id":909,"Name":"Sugars Quantity Per 100g - Total - NIP","Value":"11.7g","Description":"Sugars Quantity Per 100g - Total - NIP","SortOrder":647},{"Id":910,"Name":"Sugars Quantity Per 100g - ValueWord - NIP","Value":"11.7","Description":"Sugars Quantity Per 100g - ValueWord - NIP","SortOrder":648},{"Id":911,"Name":"Sugars Quantity Per Serve - SuffixUnits - NIP","Value":"g","Description":"Sugars Quantity Per Serve - SuffixUnits - NIP","SortOrder":650},{"Id":912,"Name":"Sugars Quantity Per Serve - Total - NIP","Value":"5.8g","Description":"Sugars Quantity Per Serve - Total - NIP","SortOrder":651},{"Id":572,"Name":"Sugars Quantity Per Serve - ValueWord - NIP","Value":"5.8","Description":"Sugars Quantity Per Serve - ValueWord - NIP","SortOrder":652}]}',
      ovencook: "False",
      vegetarian: "False",
      "hypo-allergenic": null,
      timer: null,
      dermatologistrecommended: null,
      sapdepartmentno: "47",
      allergencontains: "Gluten, Soy, Wheat",
      waterresistant: null,
      friendlydisclaimer: null,
      recyclableinformation: null,
      usageinstructions: null,
      freezable: "False",
    },
    DetailsImagePaths: [
      "https://cdn0.woolworths.media/content/wowproductimages/large/919417.jpg",
      "https://cdn0.woolworths.media/content/wowproductimages/large/919417_2.jpg",
      "https://cdn0.woolworths.media/content/wowproductimages/large/919417_3.jpg",
      "https://cdn0.woolworths.media/content/wowproductimages/large/919417_4.jpg",
      "https://cdn0.woolworths.media/content/wowproductimages/large/919417_6.jpg",
    ],
    Variety: "Loaf Thick Cut",
    Rating: {
      ReviewCount: 0,
      RatingCount: 0,
      RatingSum: 0,
      OneStarCount: 0,
      TwoStarCount: 0,
      ThreeStarCount: 0,
      FourStarCount: 0,
      FiveStarCount: 0,
      Average: 0,
      OneStarPercentage: 0,
      TwoStarPercentage: 0,
      ThreeStarPercentage: 0,
      FourStarPercentage: 0,
      FiveStarPercentage: 0,
    },
    HasProductSubs: false,
    IsSponsoredAd: false,
    AdID: null,
    AdIndex: null,
    AdStatus: null,
    IsMarketProduct: false,
    IsGiftable: false,
    Vendor: null,
    Untraceable: false,
    ThirdPartyProductInfo: null,
    MarketFeatures: null,
    MarketSpecifications: null,
    SupplyLimitSource: "ProductLimit",
    Tags: [
      {
        Content: {
          Type: "Roundel",
          Position: "Top",
          Attributes: {
            ImagePath:
              "/content/promotiontags/jupiter-roundel-hexagon-buy1-200x200.png",
            FallbackText: "Buy 1 Get 1 bonus card pack ^",
          },
        },
        TemplateId: null,
        Metadata: null,
      },
      {
        Content: {
          Type: "PromotionInformation",
          Position: "Top",
          Attributes: {
            TagLink: null,
            Text: "Earn Bonus Card Pack^ ",
            Html: '<a title="Earn Bonus Card Pack^" href="/Shop/ProductGroup/411341"><span>Earn Bonus Card Pack^ </span><i aria-hidden="true" class="iconAct-Chevron_Right"></i></a>',
            IsRegisteredRewardCardPromotion: "False",
          },
        },
        TemplateId: null,
        Metadata: null,
      },
    ],
    IsPersonalisedByPurchaseHistory: false,
    IsFromFacetedSearch: false,
    NextAvailabilityDate: null,
    NumberOfSubstitutes: 0,
    IsPrimaryVariant: false,
    VariantGroupId: 0,
    HasVariants: false,
    VariantTitle: null,
    IsTobacco: false,
    IsB2BExtendedRangeSapCategory: false,
  },
  Nutrition: null,
  VideoUrl: null,
  PrimaryCategory: {
    Department: "bakery",
    Aisle: "baked snacks & sweets",
    VisualShoppingAisleId: 19,
    DisplayOrder: 7,
    OverrideName: null,
    Instance: "Alpha",
  },
  AdditionalAttributes: {
    boxedcontents: null,
    addedvitaminsandminerals: "False",
    sapdepartmentname: "PROPRIETARY BAKERY",
    spf: null,
    haircolour: null,
    lifestyleanddietarystatement: "Halal",
    sapcategoryname: "PROPRIETARY BAKERY",
    skintype: null,
    importantinformation: null,
    allergystatement:
      "Dairy Free,Egg Free,Fish Free,Lactose Free,No Artificial Colours or Flavours,No Artificial Preservatives",
    productdepthmm: null,
    skincondition: null,
    ophthalmologistapproved: null,
    healthstarrating: "3",
    hairtype: null,
    "fragrance-free": null,
    sapsegmentname: "FRUIT LOAF/SCONE",
    suitablefor: null,
    PiesProductDepartmentsjson: '[{"Id":"1_DEB537E","Description":"Bakery"}]',
    piessubcategorynamesjson: '["Muffins, Scones & Cupcakes"]',
    sapsegmentno: "7",
    productwidthmm: null,
    contains: null,
    sapsubcategoryname: "RESALE BAKERY SNACKS",
    dermatologisttested: null,
    wool_productpackaging: null,
    dermatologicallyapproved: null,
    specialsgroupid: null,
    productimages:
      "919417.jpg,919417_2.jpg,919417_3.jpg,919417_4.jpg,919417_6.jpg",
    productheightmm: null,
    "r&r_hidereviews": null,
    microwavesafe: "False",
    "paba-free": null,
    lifestyleclaim: "HALAL",
    alcoholfree: null,
    tgawarning: null,
    activeconstituents: null,
    microwaveable: "False",
    "soap-free": null,
    countryoforigin: null,
    isexcludedfromsubstitution: "False",
    productimagecount: "5",
    "r&r_loggedinreviews": null,
    "anti-dandruff": null,
    "servingsize-total-nip": null,
    tgahealthwarninglink: null,
    allergenmaybepresent: "Sesame",
    PiesProductDepartmentNodeId: "1_DEB537E",
    parabenfree: "False",
    vendorarticleid: null,
    containsgluten: "False",
    containsnuts: "False",
    ingredients:
      "Flour, Water, Dried Sweetened Cranberries  Cranberries (5%), Sugar, Canola Oil, Wheat Gluten, Vinegar, Iodised Salt, Soy Flour, Fermented Wheat Flour, Natural Flavouring, Vegetable Emulsifiers ( 481, 472e), Vitamins (Thiamin, Folic Acid), Processing Aid (Wheat).",
    colour: null,
    manufacturer: null,
    sapcategoryno: "60",
    storageinstructions:
      "Store in a cool, dry place away from direct sunlight.",
    tgawarnings: null,
    piesdepartmentnamesjson: '["Bakery"]',
    brand: "tip top bakery",
    oilfree: null,
    fragrance: null,
    antibacterial: "False",
    "non-comedogenic": null,
    antiseptic: "False",
    bpafree: "False",
    vendorcostprice: null,
    description:
      "<br><br>Create a Café classic at home with the fruity, delicious thick-cut slices of the Tip Top Café range. Made with real fruit and full of sweet cranberries and luscious coconut. This product is limited time only, so try it quick!<br><br>Limited Edition<br><br>Made with Sweet Cranberries and Luscious Coconut<br><br>Proudly baked with Aussie Wheat<br><br>Thick cut slices",
    sweatresistant: null,
    sapsubcategoryno: "949",
    antioxidant: "False",
    claims: null,
    phbalanced: null,
    wool_dietaryclaim: null,
    ophthalmologisttested: null,
    sulfatefree: "False",
    piescategorynamesjson: '["Packaged Bread & Bakery"]',
    "servingsperpack-total-nip": null,
    nutritionalinformation:
      '{"Name":"Nutritional Information","Attributes":[{"Id":705,"Name":"Carbohydrate Quantity Per 100g - Total - NIP","Value":"45.4g","Description":"Carbohydrate Quantity Per 100g - Total - NIP","SortOrder":83},{"Id":706,"Name":"Carbohydrate Quantity Per Serve - Total - NIP","Value":"22.7g","Description":"Carbohydrate Quantity Per Serve - Total - NIP","SortOrder":87},{"Id":191,"Name":"Dietary Fibre Quantity Per 100g - Total - NIP","Value":"3.7g","Description":"Dietary Fibre Quantity Per 100g - Total - NIP","SortOrder":175},{"Id":120,"Name":"Dietary Fibre Quantity Per Serve - Total - NIP","Value":"1.8g","Description":"Dietary Fibre Quantity Per Serve - Total - NIP","SortOrder":179},{"Id":759,"Name":"Energy kJ Quantity Per 100g - Total - NIP","Value":"1210.0kJ","Description":"Energy kJ Quantity Per 100g - Total - NIP","SortOrder":239},{"Id":760,"Name":"Energy kJ Quantity Per Serve - Total - NIP","Value":"605.0kJ","Description":"Energy kJ Quantity Per Serve - Total - NIP","SortOrder":243},{"Id":253,"Name":"Fat Saturated Quantity Per 100g - Total - NIP","Value":"3.8g","Description":"Fat Saturated Quantity Per 100g - Total - NIP","SortOrder":251},{"Id":258,"Name":"Fat Saturated Quantity Per Serve - Total - NIP","Value":"1.9g","Description":"Fat Saturated Quantity Per Serve - Total - NIP","SortOrder":255},{"Id":764,"Name":"Fat Total Quantity Per 100g - Total - NIP","Value":"6.9g","Description":"Fat Total Quantity Per 100g - Total - NIP","SortOrder":263},{"Id":166,"Name":"Fat Total Quantity Per 100g - ValueWord - NIP","Value":"6.9","Description":"Fat Total Quantity Per 100g - ValueWord - NIP","SortOrder":264},{"Id":264,"Name":"Fat Total Quantity Per Serve - Total - NIP","Value":"3.4g","Description":"Fat Total Quantity Per Serve - Total - NIP","SortOrder":267},{"Id":878,"Name":"Protein Quantity Per 100g - Total - NIP","Value":"9.2g","Description":"Protein Quantity Per 100g - Total - NIP","SortOrder":587},{"Id":882,"Name":"Protein Quantity Per Serve - Total - NIP","Value":"4.6g","Description":"Protein Quantity Per Serve - Total - NIP","SortOrder":591},{"Id":477,"Name":"Serving Size - Total - NIP","Value":"50.0 G","Description":"Serving Size - Total - NIP","SortOrder":607},{"Id":544,"Name":"Servings Per Pack - Total - NIP","Value":"10.0","Description":"Servings Per Pack - Total - NIP","SortOrder":611},{"Id":491,"Name":"Sodium Quantity Per 100g - Total - NIP","Value":"306.0mg","Description":"Sodium Quantity Per 100g - Total - NIP","SortOrder":623},{"Id":495,"Name":"Sodium Quantity Per Serve - Total - NIP","Value":"153.0mg","Description":"Sodium Quantity Per Serve - Total - NIP","SortOrder":627},{"Id":908,"Name":"Sugars Quantity Per 100g - SuffixUnits - NIP","Value":"g","Description":"Sugars Quantity Per 100g - SuffixUnits - NIP","SortOrder":646},{"Id":909,"Name":"Sugars Quantity Per 100g - Total - NIP","Value":"11.7g","Description":"Sugars Quantity Per 100g - Total - NIP","SortOrder":647},{"Id":910,"Name":"Sugars Quantity Per 100g - ValueWord - NIP","Value":"11.7","Description":"Sugars Quantity Per 100g - ValueWord - NIP","SortOrder":648},{"Id":911,"Name":"Sugars Quantity Per Serve - SuffixUnits - NIP","Value":"g","Description":"Sugars Quantity Per Serve - SuffixUnits - NIP","SortOrder":650},{"Id":912,"Name":"Sugars Quantity Per Serve - Total - NIP","Value":"5.8g","Description":"Sugars Quantity Per Serve - Total - NIP","SortOrder":651},{"Id":572,"Name":"Sugars Quantity Per Serve - ValueWord - NIP","Value":"5.8","Description":"Sugars Quantity Per Serve - ValueWord - NIP","SortOrder":652}]}',
    ovencook: "False",
    vegetarian: "False",
    "hypo-allergenic": null,
    timer: null,
    dermatologistrecommended: null,
    sapdepartmentno: "47",
    allergencontains: "Gluten, Soy, Wheat",
    waterresistant: null,
    friendlydisclaimer: null,
    recyclableinformation: null,
    usageinstructions: null,
    freezable: "False",
  },
  TgaAttributes: {
    Directions: null,
    ProductWarnings: null,
    SuitableFor: null,
    StorageInstructions:
      "Store in a cool, dry place away from direct sunlight.",
  },
  DetailsImagePaths: [
    "https://cdn0.woolworths.media/content/wowproductimages/large/919417.jpg",
    "https://cdn0.woolworths.media/content/wowproductimages/large/919417_2.jpg",
    "https://cdn0.woolworths.media/content/wowproductimages/large/919417_3.jpg",
    "https://cdn0.woolworths.media/content/wowproductimages/large/919417_4.jpg",
    "https://cdn0.woolworths.media/content/wowproductimages/large/919417_6.jpg",
  ],
  NutritionalInformation: [
    {
      Name: "Energy",
      Values: {
        "Quantity Per Serving": "605.0kJ",
        "Quantity Per 100g / 100mL": "1210.0kJ",
      },
      ServingSize: "50.0 G",
      ServingsPerPack: "10.0",
    },
    {
      Name: "Protein",
      Values: {
        "Quantity Per Serving": "4.6g",
        "Quantity Per 100g / 100mL": "9.2g",
      },
      ServingSize: "50.0 G",
      ServingsPerPack: "10.0",
    },
    {
      Name: "Fat, Total",
      Values: {
        "Quantity Per Serving": "3.4g",
        "Quantity Per 100g / 100mL": "6.9g",
      },
      ServingSize: "50.0 G",
      ServingsPerPack: "10.0",
    },
    {
      Name: "– Saturated",
      Values: {
        "Quantity Per Serving": "1.9g",
        "Quantity Per 100g / 100mL": "3.8g",
      },
      ServingSize: "50.0 G",
      ServingsPerPack: "10.0",
    },
    {
      Name: "Carbohydrate",
      Values: {
        "Quantity Per Serving": "22.7g",
        "Quantity Per 100g / 100mL": "45.4g",
      },
      ServingSize: "50.0 G",
      ServingsPerPack: "10.0",
    },
    {
      Name: "– Sugars",
      Values: {
        "Quantity Per Serving": "5.8g",
        "Quantity Per 100g / 100mL": "11.7g",
      },
      ServingSize: "50.0 G",
      ServingsPerPack: "10.0",
    },
    {
      Name: "Dietary Fibre",
      Values: {
        "Quantity Per Serving": "1.8g",
        "Quantity Per 100g / 100mL": "3.7g",
      },
      ServingSize: "50.0 G",
      ServingsPerPack: "10.0",
    },
    {
      Name: "Sodium",
      Values: {
        "Quantity Per Serving": "153.0mg",
        "Quantity Per 100g / 100mL": "306.0mg",
      },
      ServingSize: "50.0 G",
      ServingsPerPack: "10.0",
    },
  ],
  RichRelevancePlacements: [
    {
      placement_name: null,
      message: null,
      Products: [],
      Items: [],
      StockcodesForDiscover: [],
    },
  ],
  Variants: [],
  VariantOptionGroups: [],
  IsTobacco: false,
  CountryOfOriginLabel: {
    PngImageFile:
      "https://cdn0.woolworths.media/content/countryoforiginlabelling/da89b14a-7a75-446e-8abd-6fca1e4c1b5e.png",
    SvgImageFile:
      "https://cdn0.woolworths.media/content/countryoforiginlabelling/da89b14a-7a75-446e-8abd-6fca1e4c1b5e.svg",
    AltText: "Made in Australia from at least 80% Australian ingredients",
    CountryOfOrigin: "Australia",
    IngredientPercentage: "80",
    Disclaimer: null,
  },
  DiagnosticsData: null,
};
